import { useEffect, useState } from 'react';
import { api } from './lib/api';

export function ManagerWorkflowPanel({ orderId, currentDate }: { orderId: string; currentDate: string }) {
  const [workflow,setWorkflow]=useState<any>(null);
  const [saving,setSaving]=useState(false);
  const load=()=>api.orderWorkflow(orderId).then(r=>setWorkflow(r.workflow));
  useEffect(()=>{void load()},[orderId]);
  if(!workflow)return <section className="px-section px-manager-editor"><p>Загружаем операции по заказу…</p></section>;
  const save=async()=>{setSaving(true);try{const r=await api.patchOrderWorkflow(orderId,workflow);setWorkflow(r.workflow)}finally{setSaving(false)}};
  const setType=(operationType:string)=>setWorkflow({...workflow,operationType,workflowStatus:operationType==='none'?'Нет запроса':operationType==='no_show'?'Зафиксировано':'Запрошено',requestedDate:operationType==='reschedule'?(workflow.requestedDate||currentDate):''});
  const statuses=workflow.operationType==='no_show'?['Зафиксировано','Оспаривается','Закрыто']:['Запрошено','Согласовано','Отклонено'];
  return <section className="px-section px-manager-editor"><div><span className="px-kicker">DEMO ОПЕРАЦИЯ</span><h2>Перенос, отмена или неявка</h2><p>Менеджер фиксирует операционный сценарий и решение по заказу. Реальный возврат денег выполняется только после подключения платёжного провайдера.</p></div><div className="px-operation-choice"><button className={workflow.operationType==='none'?'active':''} onClick={()=>setType('none')}>Без запроса</button><button className={workflow.operationType==='reschedule'?'active':''} onClick={()=>setType('reschedule')}>Перенос</button><button className={workflow.operationType==='cancel'?'active':''} onClick={()=>setType('cancel')}>Отмена</button><button className={workflow.operationType==='no_show'?'active':''} onClick={()=>setType('no_show')}>Неявка</button></div>{workflow.operationType==='reschedule'&&<label className="px-field"><span>Новая дата</span><input type="date" value={workflow.requestedDate||''} onChange={e=>setWorkflow({...workflow,requestedDate:e.target.value})}/></label>}{workflow.operationType!=='none'&&<><label className="px-field"><span>{workflow.operationType==='no_show'?'Обстоятельства неявки':'Причина / запрос клиента'}</span><textarea rows={3} value={workflow.reason||''} onChange={e=>setWorkflow({...workflow,reason:e.target.value})}/></label><label className="px-field"><span>Статус операции</span><select value={workflow.workflowStatus||statuses[0]} onChange={e=>setWorkflow({...workflow,workflowStatus:e.target.value})}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><label className="px-field"><span>Комментарий менеджера</span><textarea rows={3} value={workflow.managerNote||''} onChange={e=>setWorkflow({...workflow,managerNote:e.target.value})}/></label></>}<button className="px-button px-button-dark" onClick={save} disabled={saving}>{saving?'Сохраняем…':'Сохранить операцию'}</button><p className="px-form-note">Текущая дата заказа: {currentDate}. Все действия DEMO и попадают в журнал владельца.</p></section>;
}
