import React, { useEffect, useMemo, useState } from 'react';
import { api } from './lib/api';
import { formatUsd } from '../shared/money';

export function OwnerPage() {
  const [data,setData]=useState<any>(null);
  const [integration,setIntegration]=useState<any>(null);
  const [tilda,setTilda]=useState<any>(null);
  const [auth,setAuth]=useState<any>(null);
  const [readiness,setReadiness]=useState<any>(null);
  const [staff,setStaff]=useState<any>({mode:'demo',items:[],managementEnabled:false});
  const [webhook,setWebhook]=useState<any>(null);
  const [integrationMessage,setIntegrationMessage]=useState('');
  const [staffMessage,setStaffMessage]=useState('');
  const [saving,setSaving]=useState(false);
  const [staffSaving,setStaffSaving]=useState(false);
  const [flushing,setFlushing]=useState(false);
  const [connecting,setConnecting]=useState(false);
  const [settings,setSettings]=useState({managerSlaMinutes:15,managerNotifications:true,ownerDigest:'Ежедневно',salesFocus:'Премиум экскурсии',salesTargetMinor:500000});
  const [staffDraft,setStaffDraft]=useState({telegramUserId:'',displayName:'',role:'manager',active:true});
  const load=async()=>{
    const [overview,status,tildaStatus,authStatus,staffStatus,readinessStatus]=await Promise.all([api.ownerOverview(),api.telegramStatus(),api.tildaStatus(),api.authReadiness(),api.ownerStaff(),api.ownerReadiness()]);
    setData(overview);setSettings(overview.settings);setIntegration(status);setTilda(tildaStatus);setAuth(authStatus);setStaff(staffStatus);setReadiness(readinessStatus);
    if(status?.telegram?.botTokenConfigured){
      try{setWebhook(await api.telegramWebhookInfo())}catch{setWebhook(null)}
    }
  };
  useEffect(()=>{void load()},[]);
  const maxSource=useMemo(()=>Math.max(1,...(data?.sources??[]).map((row:any)=>row.orders)),[data]);
  if(!data)return <div className="px-owner-loading">Собираем показатели владельца…</div>;
  const save=async()=>{setSaving(true);try{const result=await api.ownerSettings(settings);setData(result);setSettings(result.settings)}finally{setSaving(false)}};
  const saveStaff=async()=>{setStaffSaving(true);setStaffMessage('');try{await api.saveStaff(staffDraft);const [nextStaff,nextAuth]=await Promise.all([api.ownerStaff(),api.authReadiness()]);setStaff(nextStaff);setAuth(nextAuth);setStaffDraft({telegramUserId:'',displayName:'',role:'manager',active:true});setStaffMessage('Доступ сотрудника сохранён.')}catch(e:any){setStaffMessage(e.message||'Не удалось сохранить сотрудника')}finally{setStaffSaving(false)}};
  const editStaff=(item:any)=>setStaffDraft({telegramUserId:item.telegramUserId,displayName:item.displayName,role:item.role,active:item.active});
  const flush=async()=>{setFlushing(true);setIntegrationMessage('');try{const result=await api.flushTelegram();setIntegration(await api.telegramStatus());setIntegrationMessage(result.tokenConfigured?`Отправлено: ${result.sent}, ошибок: ${result.failed}`:'Очередь сохранена. Bot Token ещё не настроен.')}catch(e:any){setIntegrationMessage(e.message||'Не удалось проверить очередь')}finally{setFlushing(false)}};
  const connectWebhook=async()=>{setConnecting(true);setIntegrationMessage('');try{await api.configureTelegramWebhook();setWebhook(await api.telegramWebhookInfo());setIntegration(await api.telegramStatus());setIntegrationMessage('Telegram webhook подключён к MAX TOUR.')}catch(e:any){setIntegrationMessage(e.message||'Не удалось подключить Telegram webhook')}finally{setConnecting(false)}};
  const exportReport=()=>{const payload={generatedAt:new Date().toISOString(),demo:true,metrics:data.metrics,statuses:data.statuses,sources:data.sources,recentOrders:data.recentOrders,sla:data.sla,settings:data.settings,audit:data.audit||[],auth};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='max-tour-demo-owner-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const tg=integration?.telegram;
  const canConnectWebhook=Boolean(tg?.botTokenConfigured&&tg?.webhookSecretConfigured);
  return <>
    <section className="px-owner-lead"><div><span className="px-kicker">OWNER VIEW · DEMO</span><h2>Бизнес под контролем в одном экране</h2><p>Владелец не обрабатывает каждый заказ вручную. Его задача — видеть продажи, загрузку менеджера, актуальность продукта и задавать правила работы команды.</p></div><div className="px-owner-focus"><span>Фокус продаж</span><b>{data.settings.salesFocus}</b></div></section>
    <section className="px-owner-metrics">
      <OwnerMetric label="Заказы" value={String(data.metrics.orders)} note="текущая demo-сессия"/>
      <OwnerMetric label="Объём продаж" value={formatUsd(data.metrics.grossMinor)} note="DEMO orders"/>
      <OwnerMetric label="Оплачено" value={formatUsd(data.metrics.paidMinor)} note="по demo-платежам"/>
      <OwnerMetric label="План продаж" value={`${data.metrics.targetProgressPercent??0}%`} note={`цель ${formatUsd(data.metrics.salesTargetMinor??0)}`}/>
      <OwnerMetric label="К получению" value={formatUsd(data.metrics.outstandingMinor)} note="остаток по заказам"/>
      <OwnerMetric label="Конверсия" value={`${data.metrics.conversion}%`} note="DEMO funnel"/>
      <OwnerMetric label="SLA просрочено" value={String(data.metrics.slaOverdueOrders??0)} note={`лимит ${data.sla?.managerSlaMinutes??settings.managerSlaMinutes} мин`}/>
      <OwnerMetric label="Каталог" value={`${data.metrics.publishedTours}/${data.metrics.tours}`} note="опубликовано / всего"/>
    </section>
    <section className="px-owner-grid">
      <article className="px-owner-panel"><span className="px-kicker">ОЧЕРЕДЬ КОМАНДЫ</span><h3>Что требует внимания</h3><div className="px-owner-statuses">{data.statuses.map((row:any)=><div key={row.status}><span>{row.status}</span><b>{row.count}</b></div>)}<div><span>Без контакта</span><b>{data.sla?.uncontactedOrders??0}</b></div><div><span>За SLA</span><b>{data.sla?.overdueOrders??0}</b></div></div><div className="px-owner-orders">{(data.sla?.queue??[]).filter((item:any)=>item.overdue).slice(0,4).map((item:any)=><div key={item.orderId}><div><b>{item.orderId} · {item.customer}</b><span>{item.tourTitle} · {item.assignedManager||'менеджер не назначен'}</span></div><div><strong>{item.waitingMinutes} мин</strong><small>ожидает контакта</small></div></div>)}</div><p>{data.sla?.overdueOrders?`Есть ${data.sla.overdueOrders} заказ(а), где первый контакт вышел за установленный SLA.`:'Новые заказы находятся в пределах установленного SLA.'}</p></article>
      <article className="px-owner-panel"><span className="px-kicker">КАНАЛЫ ПРОДАЖ</span><h3>Откуда приходят заказы</h3>{data.sources.map((row:any)=><div className="px-owner-source" key={row.source}><div><b>{row.source}</b><span>{row.orders} заказов · {formatUsd(row.revenueMinor)}</span></div><i><em style={{width:`${(row.orders/maxSource)*100}%`}}/></i></div>)}</article>
    </section>
    <section className="px-owner-panel px-owner-workflow"><span className="px-kicker">СОВМЕСТНАЯ РАБОТА</span><h3>Как роли связаны между собой</h3><div className="px-role-flow">{data.workflow.map((item:any,index:number)=><div key={item.role}><span>{String(index+1).padStart(2,'0')}</span><b>{item.role}</b><p>{item.action}</p>{index<data.workflow.length-1&&<em>→</em>}</div>)}</div></section>
    <section className="px-owner-grid">
      <article className="px-owner-panel"><span className="px-kicker">ПРАВИЛА РАБОТЫ · DEMO</span><h3>Настройки владельца</h3><label className="px-field"><span>SLA менеджера, минут</span><input type="number" min="5" max="120" value={settings.managerSlaMinutes} onChange={e=>setSettings({...settings,managerSlaMinutes:Number(e.target.value)})}/></label><label className="px-field"><span>План продаж, USD</span><input type="number" min="0" step="100" value={Math.round((settings.salesTargetMinor??0)/100)} onChange={e=>setSettings({...settings,salesTargetMinor:Math.max(0,Math.round(Number(e.target.value)*100))})}/></label><label className="px-field"><span>Фокус продаж</span><input value={settings.salesFocus} onChange={e=>setSettings({...settings,salesFocus:e.target.value})}/></label><label className="px-field"><span>Сводка владельцу</span><select value={settings.ownerDigest} onChange={e=>setSettings({...settings,ownerDigest:e.target.value})}><option>Отключено</option><option>Ежедневно</option><option>Еженедельно</option></select></label><label className="px-owner-check"><input type="checkbox" checked={settings.managerNotifications} onChange={e=>setSettings({...settings,managerNotifications:e.target.checked})}/><span>Уведомлять менеджеров о новых заказах</span></label><button className="px-button px-button-dark px-block" onClick={save} disabled={saving}>{saving?'Сохраняем…':'Сохранить правила'}</button><p className="px-form-note">Настройки и план хранятся в D1 текущей demo-сессии и попадают в журнал действий.</p></article>
      <article className="px-owner-panel"><span className="px-kicker">ПОСЛЕДНИЕ ЗАКАЗЫ</span><h3>Картина без перехода в Manager</h3><div className="px-owner-orders">{data.recentOrders.map((order:any)=><div key={order.id}><div><b>{order.tourTitle}</b><span>{order.customer} · {order.source}</span></div><div><strong>{formatUsd(order.totalMinor)}</strong><small>{order.status}</small></div></div>)}</div></article>
    </section>
    <section className="px-owner-panel"><div className="px-owner-audit-head"><div><span className="px-kicker">ЖУРНАЛ ДЕЙСТВИЙ · D1</span><h3>Что меняла команда</h3></div><button className="px-button px-button-dark" onClick={exportReport}>Экспорт DEMO JSON</button></div><div className="px-audit-list">{(data.audit||[]).map((item:any)=><div key={item.id}><span className={`px-audit-role role-${item.actorRole}`}>{item.actorRole}</span><div><b>{item.action}</b><p>{item.entityType} · {item.entityId}{item.actorId&&item.actorId!=='demo'?` · TG ${item.actorId}`:''}</p></div><time>{new Date(item.createdAt).toLocaleString('ru-RU')}</time></div>)}</div>{!data.audit?.length&&<p className="px-form-note">Журнал заполнится после действий менеджера, администратора или владельца.</p>}</section>
    <section className="px-owner-grid">
      <article className="px-owner-panel"><span className="px-kicker">ДОСТУПЫ КОМАНДЫ</span><h3>Telegram RBAC</h3><div className="px-owner-statuses"><div><span>Режим</span><b>{auth?.authMode??'demo'}</b></div><div><span>initData HMAC</span><b>{auth?.initDataValidationPrepared?'OK':'—'}</b></div><div><span>Bootstrap Owner</span><b>{auth?.bootstrapOwnerConfigured?'OK':'—'}</b></div><div><span>Активные сотрудники</span><b>{auth?.activeStaffAccounts??0}</b></div></div><p>{auth?.authMode==='telegram'?'Служебные разделы защищены Telegram initData и ролями Manager / Admin / Owner.':'Публичное демо оставлено в режиме demo. После добавления Bot Token и Telegram ID владельца можно включить AUTH_MODE=telegram без переделки интерфейса.'}</p>{staff?.managementEnabled&&<><div className="px-owner-orders">{staff.items.map((item:any)=><button key={item.telegramUserId} className="px-crm-edit-toggle" onClick={()=>editStaff(item)}><b>{item.displayName}</b> · {item.role} · {item.active?'активен':'отключён'} · TG {item.telegramUserId}</button>)}</div><label className="px-field"><span>Telegram user ID</span><input value={staffDraft.telegramUserId} onChange={e=>setStaffDraft({...staffDraft,telegramUserId:e.target.value})}/></label><label className="px-field"><span>Имя сотрудника</span><input value={staffDraft.displayName} onChange={e=>setStaffDraft({...staffDraft,displayName:e.target.value})}/></label><label className="px-field"><span>Роль</span><select value={staffDraft.role} onChange={e=>setStaffDraft({...staffDraft,role:e.target.value})}><option value="manager">Manager</option><option value="admin">Admin</option><option value="owner">Owner</option></select></label><label className="px-owner-check"><input type="checkbox" checked={staffDraft.active} onChange={e=>setStaffDraft({...staffDraft,active:e.target.checked})}/><span>Активный доступ</span></label><button className="px-button px-button-dark px-block" onClick={saveStaff} disabled={staffSaving}>{staffSaving?'Сохраняем…':'Сохранить сотрудника'}</button>{staffMessage&&<p className="px-form-note">{staffMessage}</p>}</>}</article>
      <article className="px-owner-panel"><span className="px-kicker">TELEGRAM INTEGRATION</span><h3>Готовность уведомлений</h3><div className="px-owner-statuses"><div><span>Bot token</span><b>{tg?.botTokenConfigured?'OK':'—'}</b></div><div><span>Webhook secret</span><b>{tg?.webhookSecretConfigured?'OK':'—'}</b></div><div><span>Manager chat</span><b>{tg?.managerChatConfigured?'OK':'—'}</b></div><div><span>Owner chat</span><b>{tg?.ownerChatConfigured?'OK':'—'}</b></div></div><p>Бизнес-события уже пишутся в D1 outbox. Пока секреты не заданы, очередь сохраняется и ничего не отправляет наружу.</p><button className="px-button px-button-dark px-block" onClick={connectWebhook} disabled={!canConnectWebhook||connecting}>{connecting?'Подключаем…':webhook?.url?'Переподключить Telegram webhook':'Подключить Telegram webhook'}</button>{webhook?.url&&<p className="px-form-note">Webhook: {webhook.url}</p>}<button className="px-button px-button-dark px-block" onClick={flush} disabled={flushing}>{flushing?'Проверяем очередь…':'Отправить очередь, если Telegram настроен'}</button>{integrationMessage&&<p className="px-form-note">{integrationMessage}</p>}</article>
    </section>
    <section className="px-owner-grid">
      <article className="px-owner-panel"><span className="px-kicker">NOTIFICATION OUTBOX</span><h3>Очередь событий</h3><div className="px-owner-statuses"><div><span>Ожидают</span><b>{integration?.outbox?.queued??0}</b></div><div><span>Отправлено</span><b>{integration?.outbox?.sent??0}</b></div><div><span>Ошибки</span><b>{integration?.outbox?.failed??0}</b></div></div><p>{integration?.readyForDelivery?'Telegram готов к доставке сообщений.':'Для реальной доставки останется добавить Telegram secrets/chat IDs. Код, webhook и очередь уже готовы.'}</p></article>
      <article className="px-owner-panel"><span className="px-kicker">TILDA INTEGRATION</span><h3>Входящий канал сайта</h3><div className="px-owner-statuses"><div><span>Webhook guard</span><b>{tilda?.configured?'OK':'—'}</b></div><div><span>Получено</span><b>{tilda?.inbox?.received??0}</b></div><div><span>Сопоставлено</span><b>{tilda?.inbox?.mapped??0}</b></div><div><span>Ошибки</span><b>{tilda?.inbox?.failed??0}</b></div></div><p>Приём форм Tilda уже реализован и защищён от повторной записи через уникальный lead ID. Для реального подключения останется задать webhook secret в Cloudflare и включить URL в настройках форм Tilda.</p></article>
    </section>
    <section className="px-owner-panel"><span className="px-kicker">PRODUCTION READINESS</span><h3>Что готово до внешних подключений</h3><div className="px-owner-statuses"><div><span>Внутренняя схема</span><b>{readiness?.preExternalImplementationComplete?'OK':'CHECK'}</b></div><div><span>D1 таблицы</span><b>{readiness?.database?.healthy?'OK':'CHECK'}</b></div><div><span>Внешних блокеров</span><b>{readiness?.externalBlockerCount??'—'}</b></div></div><div className="px-owner-orders">{(readiness?.externalBlockers??[]).map((item:any)=><div key={item.key}><div><b>{item.area}</b><span>{item.required}</span></div><div><small>ВНЕШНЯЯ НАСТРОЙКА</small></div></div>)}</div><p>{readiness?.preExternalImplementationComplete?'Код, внутренняя D1-схема, workflow и deployment-контур готовы. Список выше содержит только данные/системы, которые должны прийти от MAX TOUR или выбранного провайдера.':'Есть внутренний технический блокер — перед production activation его нужно устранить.'}</p></section>
    <section className="px-owner-panel"><span className="px-kicker">INTEGRATION BOUNDARY</span><h3>Что не подменяем демо-логикой</h3><p>Произвольный лид Tilda не превращается автоматически в экскурсионный заказ, пока MAX TOUR не подтвердит реальные поля форм и hidden ID тура. Реальный эквайринг и live inventory также подключаются только к выбранным бизнес-источникам.</p></section>
  </>;
}

function OwnerMetric({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>}
